public class Main {
    public static void main(String[] args) {
        Opg1.løsning();
        Opg2.løsning();
        Opg3.løsning();
        Opg4.løsning();
        Opg5.løsning();
        Opg6.løsning();
        Opg7.løsning();
        Opg8.løsning();
        Opg9.løsning(5);
        Opg10a.løsning(-9);
        Opg10b.løsning(-9);
        Opg12.løsning();
        Opg13.løsning();
        Opg14.løsning();
        Opg15.løsning();
        Opg16.løsning();
        Opg17.løsning();
        Opg18.løsning();
        Opg19.løsning();
        Opg20.løsning();
        Opg21.løsning();
        Opg23.Løsning();
        Opg24.Løsning();
        Opg26.Løsning();
        Opg27.Løsning();
        Opg28.Løsning();
        Opg30.Løsning1();
        Opg30.Løsning2();
        Opg30.Løsning3();
    }
}
